[
    { "id": 1, "name": "Rice Mask", "description": "An organic rice face mask", "price": 10, "category": "Beauty" },
    { "id": 2, "name": "Banana Leaf Plate", "description": "Eco-friendly plate made from banana leaves", "price": 5, "category": "Eco" },
    { "id": 3, "name": "Aloe Vera Gel", "description": "Soothing gel made from natural aloe vera", "price": 15, "category": "Beauty" },
    { "id": 4, "name": "Coconut Oil", "description": "Cold-pressed coconut oil", "price": 12, "category": "Beauty" },
    { "id": 5, "name": "Herbal Shampoo", "description": "Organic shampoo with herbal ingredients", "price": 8, "category": "Beauty" },
    { "id": 6, "name": "Green Tea Extract", "description": "Natural green tea extract for skin", "price": 20, "category": "Beauty" },
    { "id": 7, "name": "Organic Soap", "description": "Handmade organic soap", "price": 7, "category": "Beauty" },
    { "id": 8, "name": "Bamboo Toothbrush", "description": "Eco-friendly toothbrush made of bamboo", "price": 3, "category": "Eco" },
    { "id": 9, "name": "Herbal Oil", "description": "Herbal oil for hair and skin care", "price": 18, "category": "Beauty" },
    { "id": 10, "name": "Charcoal Mask", "description": "Detoxifying charcoal face mask", "price": 25, "category": "Beauty" },
    { "id": 11, "name": "Tea Tree Oil", "description": "Organic tea tree oil", "price": 22, "category": "Beauty" },
    { "id": 12, "name": "Lavender Oil", "description": "Pure lavender essential oil", "price": 30, "category": "Beauty" },
    { "id": 13, "name": "Beeswax Lip Balm", "description": "Natural beeswax lip balm", "price": 4, "category": "Beauty" },
    { "id": 14, "name": "Coconut Milk Shampoo", "description": "Nourishing coconut milk shampoo", "price": 14, "category": "Beauty" },
    { "id": 15, "name": "Exfoliating Scrub", "description": "Gentle exfoliating scrub", "price": 16, "category": "Beauty" },
    { "id": 16, "name": "Herbal Tea", "description": "Natural herbal tea for relaxation", "price": 6, "category": "Food & Beverage" },
    { "id": 17, "name": "Coconut Water", "description": "Fresh coconut water", "price": 5, "category": "Food & Beverage" },
    { "id": 18, "name": "Organic Rice", "description": "100% organic rice", "price": 4, "category": "Food & Beverage" },
    { "id": 19, "name": "Banana Chips", "description": "Crispy banana chips", "price": 3, "category": "Food & Beverage" },
    { "id": 20, "name": "Rice Flour", "description": "Organic rice flour", "price": 7, "category": "Food & Beverage" },
    { "id": 21, "name": "Green Smoothie", "description": "Nutrient-packed green smoothie", "price": 12, "category": "Food & Beverage" },
    { "id": 22, "name": "Oatmeal", "description": "Healthy oatmeal for breakfast", "price": 4, "category": "Food & Beverage" },
    { "id": 23, "name": "Avocado Oil", "description": "Cold-pressed avocado oil", "price": 25, "category": "Beauty" },
    { "id": 24, "name": "Matcha Powder", "description": "Premium quality matcha powder", "price": 30, "category": "Food & Beverage" },
    { "id": 25, "name": "Organic Almond Butter", "description": "Pure almond butter", "price": 22, "category": "Food & Beverage" }
    
        { "id": 26, "name": "John Doe", "email": "john@example.com", "password": "password123", "address": "123 Main St, City, Country" },
        { "id": 27, "name": "Jane Smith", "email": "jane@example.com", "password": "password456", "address": "456 Elm St, City, Country" },
        { "id": 28, "name": "Alice Johnson", "email": "alice@example.com", "password": "password789", "address": "789 Oak St, City, Country" },
        { "id": 29, "name": "Bob Brown", "email": "bob@example.com", "password": "password101", "address": "101 Pine St, City, Country" },
        { "id": 30, "name": "Charlie Davis", "email": "charlie@example.com", "password": "password102", "address": "102 Maple St, City, Country" },
        { "id": 31, "name": "David Evans", "email": "david@example.com", "password": "password103", "address": "103 Birch St, City, Country" },
        { "id": 32, "name": "Eve White", "email": "eve@example.com", "password": "password104", "address": "104 Cedar St, City, Country" },
        { "id": 33, "name": "Frank Harris", "email": "frank@example.com", "password": "password105", "address": "105 Pineapple St, City, Country" },
        { "id": 34, "name": "Grace Clark", "email": "grace@example.com", "password": "password106", "address": "106 Apple St, City, Country" },
        { "id": 35, "name": "Hank Lewis", "email": "hank@example.com", "password": "password107", "address": "107 Peach St, City, Country" },
        { "id": 36, "name": "Ivy Young", "email": "ivy@example.com", "password": "password108", "address": "108 Mango St, City, Country" },
        { "id": 37, "name": "Jack King", "email": "jack@example.com", "password": "password109", "address": "109 Banana St, City, Country" },
        { "id": 38, "name": "Kathy Scott", "email": "kathy@example.com", "password": "password110", "address": "110 Cherry St, City, Country" },
        { "id": 39, "name": "Liam Moore", "email": "liam@example.com", "password": "password111", "address": "111 Apricot St, City, Country" },
        { "id": 40, "name": "Mia Harris", "email": "mia@example.com", "password": "password112", "address": "112 Pear St, City, Country" },
        { "id": 41, "name": "Nina Rodriguez", "email": "nina@example.com", "password": "password113", "address": "113 Grape St, City, Country" },
        { "id": 42, "name": "Oscar Walker", "email": "oscar@example.com", "password": "password114", "address": "114 Kiwi St, City, Country" },
        { "id": 43, "name": "Paul Hill", "email": "paul@example.com", "password": "password115", "address": "115 Watermelon St, City, Country" },
        { "id": 44, "name": "Quincy Adams", "email": "quincy@example.com", "password": "password116", "address": "116 Pine St, City, Country" },
        { "id": 45, "name": "Rachel Perez", "email": "rachel@example.com", "password": "password117", "address": "117 Oak St, City, Country" }
        
      ]
      
  